export const HORSE_NAMES = [
  'Thunder Bolt',
  'Shadowfax',
  'Crimson Fire',
  'Golden Arrow',
  'Midnight Star',
  'Storm Chaser',
  'Rapid River',
  'Galaxy Runner',
  'Iron Heart',
  'Wind Whisper',
  'Solar Flare',
  'Noble Steed',
  'Velocity',
  'Dark Knight',
  'Silver Bullet',
  'Ocean Breeze',
  'Desert Storm',
  'Royal Spirit',
  'Magic Dust',
  'Phantom Ghost',
]

export const HORSE_COLORS = [
  { colorName: 'Scarlet Red', colorHex: '#FF2400' },
  { colorName: 'Lime Green', colorHex: '#32CD32' },
  { colorName: 'Royal Blue', colorHex: '#4169E1' },
  { colorName: 'Hot Pink', colorHex: '#FF69B4' },
  { colorName: 'Electric Purple', colorHex: '#BF00FF' },
  { colorName: 'Cyan', colorHex: '#00FFFF' },
  { colorName: 'Goldenrod', colorHex: '#DAA520' },
  { colorName: 'Crimson', colorHex: '#DC143C' },
  { colorName: 'Teal', colorHex: '#008080' },
  { colorName: 'Indigo', colorHex: '#4B0082' },
  { colorName: 'Forest Green', colorHex: '#228B22' },
  { colorName: 'Steel Blue', colorHex: '#4682B4' },
  { colorName: 'Pumpkin Orange', colorHex: '#FF7518' },
  { colorName: 'Amethyst', colorHex: '#9966CC' },
  { colorName: 'Navy Blue', colorHex: '#000080' },
  { colorName: 'Turquoise', colorHex: '#40E0D0' },
  { colorName: 'Sunflower', colorHex: '#FFDA03' },
  { colorName: 'Bronze', colorHex: '#CD7F32' },
  { colorName: 'Charcoal Grey', colorHex: '#36454F' },
  { colorName: 'Midnight Black', colorHex: '#191970' },
]
